export const USER_LIST = 'USER_LIST'
export const USER_COUNT = 'USER_COUNT'
export const USER_PAGINATION = 'USER_PAGINATION'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED'

export const GRAPH_USER_DISTRIBUTION = 'GRAPH_USER_DISTRIBUTION'
export const GRAPH_REQUEST = 'GRAPH_REQUEST'
export const GRAPH_REQUEST_FAILED = 'GRAPH_REQUEST_FAILED'
