export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const ADMIN_INFO = 'ADMIN_INFO'
export const ADMIN_LIST = 'ADMIN_LIST'
export const ADMIN_COUNT = 'ADMIN_COUNT'
export const ADMIN_PAGINATION = 'ADMIN_PAGINATION'
export const ADMIN_REQUEST = 'ADMIN_REQUEST'
export const ADMIN_REQUEST_FAILED = 'ADMIN_REQUEST_FAILED'

export const USER_LIST = 'USER_LIST'
export const USER_COUNT = 'USER_COUNT'
export const USER_PAGINATION = 'USER_PAGINATION'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED'

export const GRAPH_USER_DISTRIBUTION = 'GRAPH_USER_DISTRIBUTION'
export const GRAPH_REQUEST = 'GRAPH_REQUEST'
export const GRAPH_REQUEST_FAILED = 'GRAPH_REQUEST_FAILED'
